name: CI

on: [push]

jobs:
  setup:
    name: Install dependencies
    run: npm install

  lint:
    name: Lint
    run: npm run lint

  build:
    name: Build
    run: npm run build

  test:
    name: Unit test
    run: npm run test:unit

workflows:
  ci:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - build:
          requires:
            - setup
      - test:
          requires:
            - setup
