name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: maven package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
      - run: npm install
      - name: Lint
      - run: npm run lint
      - name: Build
      - run: npm run build
      - name: Unit test
      - run: npm run test:unit
